extends Node

const FULL_DECK = [
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ANGUSTIAS_PER",
	"ENRIQUETA_PER",
	"GERTRUDIS_PER",
	"GREGORIO_PER",
	"JEREMIAS_PER",
	"LIBERTO_PER",
	"URSULA_PER"]
